# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.TextField(default=datetime.datetime(2016, 7, 22, 1, 35, 48, 187693, tzinfo=utc), max_length=2000),
            preserve_default=False,
        ),
    ]
