# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
