# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20160722_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
