# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20160722_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
