# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20160723_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
