# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
